### ISSUE TITLE
Provide a theme name for the cli

### ISSUE THREAD

**Issue by pirix-gh** [horyus/typedoc-thunder-theme#1]
Can you please provide a command to install the theme ?

``` sh
npx typedoc --out docs ./src/ --theme typedoc-thunder-theme
```

I can't get it installed

**Comment by mortimr** [comment]
Hi,

Can you try

```
npx typedoc --out docs ./src/ --theme ./node_modules/typedoc-thunder-theme/bin/default/
```

and tell me if it works ?

**Comment by pirix-gh** [comment]
Yes, it works. Thanks. Maybe you could provide a name for your theme, or just add this to the Readme
